config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :dice_rolls, except: %i[edit update destroy]
  resources :dice_types  do
    patch :order, on: :member
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dice_roll.rb
class DiceRoll < ApplicationRecord
  belongs_to :user
  belongs_to :dice_type
  belongs_to :roll

  validates :dice_type_id, presence: true
end

app/models/dice_type.rb
class DiceType < ApplicationRecord
  acts_as_list
  has_many :dice_rolls, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :sides, presence: true, numericality: { only_integer: true, greater_than: 0 }
  scope :ordered, -> { order(position: :asc) }
end

app/models/roll.rb
class Roll < ApplicationRecord
  belongs_to :user
  has_many :dice_rolls, dependent: :destroy

  accepts_nested_attributes_for :dice_rolls, allow_destroy: true, reject_if: :all_blank
  scope :ordered, -> { order(created_at: :desc) }

  def total
    dice_rolls.map(&:roll_result).sum
  end

  def max_total
    dice_rolls.map { |dice_roll| dice_roll.dice_type.sides * dice_roll.quantity }.sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum role: { user: 0, admin: 1 }
         has_many :dice_rolls, dependent: :destroy
         has_many :dice_types, dependent: :destroy
         has_many :rolls, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/dice_rolls_controller.rb
class DiceRollsController < ApplicationController

  # POST /dice_rolls or /dice_rolls.json
  def create
    @roll = current_user.rolls.build(dice_roll_params)
    @roll.dice_rolls = DiceRollerService.new(@roll).roll_dice

    respond_to do |format|
      if @roll.save
        format.turbo_stream
        format.html { redirect_to root_path, notice: "Roll was successfully created." }
      end
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def dice_roll_params
      params.require(:roll).permit(dice_rolls_attributes: %i[id _destroy dice_type_id quantity])
    end
end

app/controllers/dice_types_controller.rb
class DiceTypesController < ApplicationController
  before_action :set_dice_type, only: %i[show edit update destroy order]
  before_action :authorize_admin!
  # GET /dice_types or /dice_types.json
  def index
    @dice_types = DiceType.ordered
  end

  # GET /dice_types/1 or /dice_types/1.json
  def show; end

  # GET /dice_types/new
  def new
    @dice_type = DiceType.new
  end

  # GET /dice_types/1/edit
  def edit; end

  # POST /dice_types or /dice_types.json
  def create
    @dice_type = DiceType.new(dice_type_params)

    respond_to do |format|
      if @dice_type.save
        format.html { redirect_to dice_type_url(@dice_type), notice: 'Dice type was successfully created.' }
        format.json { render :show, status: :created, location: @dice_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dice_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dice_types/1 or /dice_types/1.json
  def update
    respond_to do |format|
      if @dice_type.update(dice_type_params)
        format.html { redirect_to dice_type_url(@dice_type), notice: 'Dice type was successfully updated.' }
        format.json { render :show, status: :ok, location: @dice_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dice_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dice_types/1 or /dice_types/1.json
  def destroy
    @dice_type.destroy

    respond_to do |format|
      format.html { redirect_to dice_types_url, notice: 'Dice type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def order
    position = params[:dice_type][:position].to_i
    @dice_type.insert_at(position)
    head :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dice_type
    @dice_type = DiceType.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def dice_type_params
    params.require(:dice_type).permit(:name, :sides, :position)
  end

  def authorize_admin!
    redirect_to root_path, alert: 'You are not authorized to access that page.' unless current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @dice_types = DiceType.ordered
    # @dice_rolls = current_user.dice_rolls.order(created_at: :desc)
    @rolls = current_user.rolls.ordered

    @roll = current_user.rolls.build
    @roll.dice_rolls.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dice_rolls_helper.rb
module DiceRollsHelper
end

app/helpers/dice_types_helper.rb
module DiceTypesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dice_rolls/_dice_roll.html.erb
<div id="<%= dom_id dice_roll %>">
  <p>
    <strong>Dice type:</strong>
    <%= dice_roll.dice_type.name %> * <%= dice_roll.quantity %>
  </p>
  <p>
    <strong>Roll result:</strong>
    <%= dice_roll.roll_result %> / <%= dice_roll.dice_type.sides * dice_roll.quantity %>
  </p>
  <p>
    <strong>Created at:</strong>
    <%= time_ago_in_words(dice_roll.created_at) + " ago" %>
  </p>
</div>

app/views/dice_rolls/_dice_roll_fields.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.collection_select :dice_type_id, @dice_types, :id, :name %>
  <%= f.number_field :quantity, in: 1..10, value: 1 %>
  <%= f.hidden_field :_destroy %>
  <button type="button" data-action="nested-form#remove">Remove Roll</button>
</div>

app/views/dice_rolls/_form.html.erb
<%= form_with(model: dice_roll) do |form| %>
  <% if dice_roll.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dice_roll.errors.count, "error") %> prohibited this dice_roll from being saved:</h2>

      <ul>
        <% dice_roll.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :dice_type_id, style: "display: block" %>
    <%= form.text_field :dice_type_id %>
  </div>

  <div>
    <%= form.label :roll_result, style: "display: block" %>
    <%= form.number_field :roll_result %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dice_rolls/create.turbo_stream.erb
<%= turbo_stream.prepend "rolls", 
    partial: "rolls/roll", 
    locals: { roll: @roll } %>

app/views/dice_rolls/edit.html.erb
<h1>Editing dice roll</h1>

<%= render "form", dice_roll: @dice_roll %>

<br>

<div>
  <%= link_to "Show this dice roll", @dice_roll %> |
  <%= link_to "Back to dice rolls", dice_rolls_path %>
</div>

app/views/dice_rolls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dice rolls</h1>

<div id="dice_rolls">
  <% @dice_rolls.each do |dice_roll| %>
    <%= render dice_roll %>
    <p>
      <%= link_to "Show this dice roll", dice_roll %>
    </p>
  <% end %>
</div>

<%= link_to "New dice roll", new_dice_roll_path %>

app/views/dice_rolls/new.html.erb
<h1>New dice roll</h1>

<%= render "form", dice_roll: @dice_roll %>

<br>

<div>
  <%= link_to "Back to dice rolls", dice_rolls_path %>
</div>

app/views/dice_rolls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dice_roll %>

<div>
  <%= link_to "Edit this dice roll", edit_dice_roll_path(@dice_roll) %> |
  <%= link_to "Back to dice rolls", dice_rolls_path %>

  <%= button_to "Destroy this dice roll", @dice_roll, method: :delete %>
</div>

app/views/dice_types/_dice_type.html.erb
<div id="<%= dom_id dice_type %>">
  <p>
    <strong>Name:</strong>
    <%= dice_type.name %>
  </p>

  <p>
    <strong>Sides:</strong>
    <%= dice_type.sides %>
  </p>

</div>

app/views/dice_types/_form.html.erb
<%= form_with(model: dice_type) do |form| %>
  <% if dice_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dice_type.errors.count, "error") %> prohibited this dice_type from being saved:</h2>

      <ul>
        <% dice_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :sides, style: "display: block" %>
    <%= form.number_field :sides %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dice_types/edit.html.erb
<h1>Editing dice type</h1>

<%= render "form", dice_type: @dice_type %>

<br>

<div>
  <%= link_to "Show this dice type", @dice_type %> |
  <%= link_to "Back to dice types", dice_types_path %>
</div>

app/views/dice_types/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Dice types</h1>
<div id="dice_types" 
  data-controller="sortable" 
  data-sortable-animation-value="150"
  data-sortable-resource-name-value="dice_type">
  <% @dice_types.each do |dice_type| %>
    <div data-sortable-update-url="<%= order_dice_type_path(dice_type) %>">
      <%= render dice_type %>
      <p>
        <%= link_to "Show this dice type", dice_type %>
      </p>
    </div>
  <% end %>
</div>
<%= link_to "New dice type", new_dice_type_path %>

app/views/dice_types/new.html.erb
<h1>New dice type</h1>

<%= render "form", dice_type: @dice_type %>

<br>

<div>
  <%= link_to "Back to dice types", dice_types_path %>
</div>

app/views/dice_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dice_type %>

<div>
  <%= link_to "Edit this dice type", edit_dice_type_path(@dice_type) %> |
  <%= link_to "Back to dice types", dice_types_path %>

  <%= button_to "Destroy this dice type", @dice_type, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>On A Roll</h1>
<%= form_with model: @roll, 
    url: dice_rolls_path,
    method: :post, 
    local: true, 
    data: { 
        controller: 'nested-form', 
        nested_form_wrapper_selector_value: '.nested-form-wrapper' 
    } do |f| %>
  <template data-nested-form-target="template">
    <%= f.fields_for :dice_rolls, DiceRoll.new, child_index: "NEW_RECORD" do |dice_roll_fields| %>
      <%= render "dice_rolls/dice_roll_fields", f: dice_roll_fields %>
    <% end %>
  </template>
  <%= f.fields_for :dice_rolls do |dice_roll_fields| %>
    <%= render "dice_rolls/dice_roll_fields", f: dice_roll_fields %>
  <% end %>
  <div data-nested-form-target="target"></div>
  <button type="button" data-action="nested-form#add">Add Roll</button>
  <%= f.submit "Roll Dice!" %>
<% end %>
<div id="rolls">
  <% @rolls.each do |roll| %>
    <%= render "rolls/roll", roll: roll %>
  <% end %>
</div>

app/views/rolls/_roll.html.erb
<div id="<%= dom_id(roll) %>">
  <p>You rolled <%= roll.total %> / <%= roll.max_total %></p>
  <% roll.dice_rolls.includes(:dice_type).order('dice_types.position ASC').each do |dice_roll| %>
    <%= render "dice_rolls/dice_roll", dice_roll: dice_roll %>
  <% end %>
  <hr />
</div>